// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WidgetServer.Data;

namespace WidgetServer.Migrations
{
    [DbContext(typeof(WidgetsDataContext))]
    [Migration("20190716105534_EmailAddressAsID")]
    partial class EmailAddressAsID
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WidgetServer.Models.User", b =>
                {
                    b.Property<string>("EmailAddress")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Familyname");

                    b.Property<string>("GoogleID");

                    b.Property<string>("Name");

                    b.HasKey("EmailAddress");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
